# Generated by Django 6.0.5 on 2026-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
